"""Crypto-native factor mining package.

The package has two clear modules:

- `quantaalpha_crypto.evaluation`: evaluates supplied Directional Factors.
- `quantaalpha_crypto.mining`: orchestrates local mining runs around evaluation.

The top-level package re-exports the stable public interface for convenience.
"""

from quantaalpha_crypto.evaluation import (
    CandidateFactorLibraryEntry,
    CryptoPanel,
    FactorEvaluation,
    FactorEvaluationReport,
    FactorGateResult,
    GateStatus,
    PortfolioBacktestConfig,
    PortfolioBacktestResult,
    portfolio_backtest_result_to_dict,
    WalkForwardWindow,
    append_candidate_factor_library_entry,
    build_crypto_panel,
    build_walk_forward_windows,
    evaluate_directional_factor,
    run_crypto_portfolio_backtest,
    load_candidate_factor_library,
)
from quantaalpha_crypto.data import (
    BinanceCryptoPanelData,
    BinanceLocalDataConfig,
    load_binance_crypto_panel_data,
)
from quantaalpha_crypto.mining import (
    AnthropicCompletionClient,
    AnthropicCryptoFactorProposalProvider,
    AnthropicCryptoFactorRepairProvider,
    BatchFactorResult,
    BatchFactorRunResult,
    CryptoFactorWorkspace,
    CryptoFactorSource,
    CryptoMiningRoundConfig,
    CryptoMiningRoundResult,
    FactorProposalCandidate,
    FactorProposalContext,
    FactorProposalProvider,
    FactorProposalResult,
    FactorRepairContext,
    FactorRepairProvider,
    FactorRepairResult,
    FactorTimingConfig,
    DEFAULT_ANTHROPIC_MODEL,
    OriginalFlowCryptoMiningRunConfig,
    ProviderConfig,
    RejectedFactorDiagnostic,
    build_round_feedback_context,
    create_crypto_factor_workspace,
    run_factor_proposal_provider,
    run_factor_proposal_provider_with_repair,
    run_local_crypto_mining_round,
    run_crypto_factor_sources,
    run_supplied_factor_callables,
    write_portfolio_backtest_result,
    parse_original_flow_crypto_mining_run_config,
)

__all__ = [
    "CryptoPanel",
    "FactorEvaluation",
    "FactorEvaluationReport",
    "FactorGateResult",
    "GateStatus",
    "PortfolioBacktestConfig",
    "PortfolioBacktestResult",
    "portfolio_backtest_result_to_dict",
    "CandidateFactorLibraryEntry",
    "BatchFactorResult",
    "BatchFactorRunResult",
    "BinanceCryptoPanelData",
    "BinanceLocalDataConfig",
    "AnthropicCompletionClient",
    "AnthropicCryptoFactorProposalProvider",
    "AnthropicCryptoFactorRepairProvider",
    "CryptoMiningRoundConfig",
    "CryptoMiningRoundResult",
    "FactorProposalCandidate",
    "FactorProposalContext",
    "FactorProposalProvider",
    "FactorProposalResult",
    "FactorRepairContext",
    "FactorRepairProvider",
    "FactorRepairResult",
    "FactorTimingConfig",
    "DEFAULT_ANTHROPIC_MODEL",
    "OriginalFlowCryptoMiningRunConfig",
    "ProviderConfig",
    "RejectedFactorDiagnostic",
    "WalkForwardWindow",
    "CryptoFactorWorkspace",
    "CryptoFactorSource",
    "build_round_feedback_context",
    "build_crypto_panel",
    "build_walk_forward_windows",
    "evaluate_directional_factor",
    "run_crypto_portfolio_backtest",
    "write_portfolio_backtest_result",
    "append_candidate_factor_library_entry",
    "load_candidate_factor_library",
    "load_binance_crypto_panel_data",
    "create_crypto_factor_workspace",
    "run_factor_proposal_provider",
    "run_factor_proposal_provider_with_repair",
    "run_local_crypto_mining_round",
    "run_crypto_factor_sources",
    "run_supplied_factor_callables",
    "parse_original_flow_crypto_mining_run_config",
]
